[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask==3.1.0",
    "numpy>=2.2.5",
    "openai>=1.75.0",
    "requests>=2.32.3",
    "tiktoken>=0.9.0",
]
